/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkinEditorRouteImport } from './routes/skin-editor'
import { Route as ShapeGeneratorRouteImport } from './routes/shape-generator'
import { Route as PixelArtRouteImport } from './routes/pixel-art'
import { Route as GradientRouteImport } from './routes/gradient'
import { Route as IndexRouteImport } from './routes/index'

const SkinEditorRoute = SkinEditorRouteImport.update({
  id: '/skin-editor',
  path: '/skin-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const ShapeGeneratorRoute = ShapeGeneratorRouteImport.update({
  id: '/shape-generator',
  path: '/shape-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const PixelArtRoute = PixelArtRouteImport.update({
  id: '/pixel-art',
  path: '/pixel-art',
  getParentRoute: () => rootRouteImport,
} as any)
const GradientRoute = GradientRouteImport.update({
  id: '/gradient',
  path: '/gradient',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gradient': typeof GradientRoute
  '/pixel-art': typeof PixelArtRoute
  '/shape-generator': typeof ShapeGeneratorRoute
  '/skin-editor': typeof SkinEditorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gradient': typeof GradientRoute
  '/pixel-art': typeof PixelArtRoute
  '/shape-generator': typeof ShapeGeneratorRoute
  '/skin-editor': typeof SkinEditorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gradient': typeof GradientRoute
  '/pixel-art': typeof PixelArtRoute
  '/shape-generator': typeof ShapeGeneratorRoute
  '/skin-editor': typeof SkinEditorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gradient'
    | '/pixel-art'
    | '/shape-generator'
    | '/skin-editor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gradient' | '/pixel-art' | '/shape-generator' | '/skin-editor'
  id:
    | '__root__'
    | '/'
    | '/gradient'
    | '/pixel-art'
    | '/shape-generator'
    | '/skin-editor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GradientRoute: typeof GradientRoute
  PixelArtRoute: typeof PixelArtRoute
  ShapeGeneratorRoute: typeof ShapeGeneratorRoute
  SkinEditorRoute: typeof SkinEditorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skin-editor': {
      id: '/skin-editor'
      path: '/skin-editor'
      fullPath: '/skin-editor'
      preLoaderRoute: typeof SkinEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shape-generator': {
      id: '/shape-generator'
      path: '/shape-generator'
      fullPath: '/shape-generator'
      preLoaderRoute: typeof ShapeGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pixel-art': {
      id: '/pixel-art'
      path: '/pixel-art'
      fullPath: '/pixel-art'
      preLoaderRoute: typeof PixelArtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gradient': {
      id: '/gradient'
      path: '/gradient'
      fullPath: '/gradient'
      preLoaderRoute: typeof GradientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GradientRoute: GradientRoute,
  PixelArtRoute: PixelArtRoute,
  ShapeGeneratorRoute: ShapeGeneratorRoute,
  SkinEditorRoute: SkinEditorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
